server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zhuowang_exam
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.145.3
    database: 0
mybatis:
  type-aliases-package: com.gaofv.entity
